apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: monitoring
spec:
  interval: 10m
  chart:
    spec:
      chart: loki
      version: "6.*"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      interval: 12h
  values:
    deploymentMode: SingleBinary

    loki:
      auth_enabled: false
      commonConfig:
        replication_factor: 1
      schemaConfig:
        configs:
          - from: "2024-01-01"
            store: tsdb
            object_store: s3
            schema: v13
            index:
              prefix: loki_index_
              period: 24h
      storage:
        type: s3
        bucketNames:
          chunks: ${cluster_name}-loki
          ruler: ${cluster_name}-loki
          admin: ${cluster_name}-loki
        s3:
          region: ${aws_region}

    serviceAccount:
      create: true
      name: loki

    # Single binary (SimpleScalable for prod HA)
    singleBinary:
      replicas: 1

    # Must be explicitly zeroed when using SingleBinary mode
    # Set replicas: 2 and update deploymentMode for prod HA
    write:
      replicas: 0
    read:
      replicas: 0
    backend:
      replicas: 0

    # Disable memcached caching
    chunksCache:
      enabled: false

    resultsCache:
      enabled: false

    # Gateway routes reads/writes to the correct component
    gateway:
      enabled: true
      replicas: 1
