apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: external-secrets
spec:
  interval: 10m
  chart:
    spec:
      chart: external-secrets
      version: "0.*"
      sourceRef:
        kind: HelmRepository
        name: external-secrets
        namespace: flux-system
      interval: 12h
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    replicaCount: 1

    serviceAccount:
      create: true
      name: external-secrets

    tolerations:
      - key: CriticalAddonsOnly
        operator: Exists

    nodeSelector:
      node-role: system

    webhook:
      tolerations:
        - key: CriticalAddonsOnly
          operator: Exists
      nodeSelector:
        node-role: system

    certController:
      tolerations:
        - key: CriticalAddonsOnly
          operator: Exists
      nodeSelector:
        node-role: system
