apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: karpenter
  namespace: karpenter
spec:
  interval: 10m
  chart:
    spec:
      chart: karpenter
      version: "1.*"
      sourceRef:
        kind: HelmRepository
        name: karpenter
        namespace: flux-system
      interval: 12h
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    settings:
      clusterName: ${cluster_name}
      interruptionQueue: ${cluster_name}-karpenter

    serviceAccount:
      create: true
      name: karpenter

    replicas: 1

    nodeSelector:
      kubernetes.io/os: linux
    tolerations:
      - key: CriticalAddonsOnly
        operator: Exists

    controller:
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
        limits:
          cpu: 1
          memory: 1Gi
