name: Renovate

on:
  schedule:
    # Run Mon–Fri at 8am UTC 
    - cron: "0 8 * * 1-5"
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v41
        with:
          configurationFile: .github/renovate.json
        env:
          RENOVATE_TOKEN: ${{ secrets.RENOVATE_TOKEN }}
